# Generated by Django 5.0.4 on 2024-06-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='email_is_verified',
        ),
    ]
